name: Setup step for bungeegum CI

inputs:
  platform:
    required: true
    type: string
    
  build_type:
    required: true
    type: string
        
runs:
  using: "composite"
  steps:
    - name: Set Environment Variables
      shell: bash
      run: |
        # Set Environment Variables
        echo "DILIGENT_TARGET_PLATFORM=${{inputs.platform}}" >> $GITHUB_ENV

