name: macos

on:
  workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DBUNGEEGUM_BUILD_TEST:BOOL=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target bungeegum_test --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ${{github.workspace}}/build/test/bungeegum_test

