name: scheduled release ubuntu

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: mesa-common-dev mesa-utils libgl-dev libgl1-mesa-dev
        version: 1.0

    - name: Install xmllint
      run: sudo apt-get install -y libxml2-utils

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DBUNGEEGUM_BUILD_TEST:BOOL=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target bungeegum_test --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ${{github.workspace}}/build/test/bungeegum_test

