name: Windows CI

on: 
  workflow_dispatch
  
jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform: ["Win32"]
        build_type: ["Debug", "Release"]

    name: Windows -> ${{ matrix.platform }} (${{ matrix.build_type }})

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup
      if:   success()
      uses: ${{github.repository/.github/workflows/setup.yaml}}
      with:
        platform: ${{ matrix.platform }}
        build_type: ${{ matrix.build_type }}

    # - name: Configure
    #   if:   success()
    #   uses: ./.github/workflows/configure.yaml
    #   with:
    #     build-type: ${{ matrix.build_type }}
    #     cmake-args: -DBUNGEEGUM_BUILD_TEST:BOOL=ON

    # - name: Build
    #   id:   build
    #   if:   success()
    #   uses: ./.github/workflows/build.yaml
    #   with:
    #     cmake-args: -DBUNGEEGUM_BUILD_TEST:BOOL=ON

    # - name: Test
    #   if:   success()
    #   uses: ./.github/workflows/test.yaml
    #   with:
    #     build-args: ${{ matrix.build_args }}
