name: Windows CI

on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
  
jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: ["Debug", "Release"]

    name: Win32 (${{ matrix.build_type }})

    steps:
      - uses: actions/checkout@v3

      - name: Configure
        run: cmake -B ${{ github.workspace }}/build -DBUNGEEGUM_BUILD_TEST:BOOL=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --target bungeegum_test --config ${{ matrix.build_type }}

      - name: Test
        run: ${{ github.workspace }}/build/test/${{ matrix.build_type }}/bungeegum_test.exe
